site_name: acc
site_description: Airplane Consumption Calculator
repo_url: https://github.com/An4ik/ACC
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/An4ik">An4ik</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
