# Generated by Django 2.1.1 on 2018-09-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fuel_tank', models.PositiveIntegerField(verbose_name='fuel tank')),
                ('consumption', models.FloatField(verbose_name='consumption')),
            ],
        ),
    ]
